### ISSUE TITLE
What is that for ?

### ISSUE THREAD

**Issue by Fausto95** [flowck/proxypay-api#5]
Hey,
Is that some kinda of TPA proxy payment with Node JS?

**Comment by firminochangani** [comment]
@Fausto95, this repository is an implementation of ProxyPay REST API with Nodejs. ProxyPay is a service that allow software / applications to generate ATMs reference codes used to process payments through AMTs in Angola.

**Comment by Fausto95** [comment]
Nice, I’m Angolan too.
And I really think the Multicaixa network should release an api to make easy online payments using debit card.

**Comment by firminochangani** [comment]
Ahm cool. This will not happen soon due to security concerns.

**Comment by Fausto95** [comment]
They could make it. It’s way too simple.
It’s just the same thing as the TPA works.

**Comment by firminochangani** [comment]
The main issue is not technical, it's a matter of an oriented mindset.

**Comment by Fausto95** [comment]
Hoping they'll change it.

**Comment by Fausto95** [comment]
How do you create a proxy pay account ?

**Comment by firminochangani** [comment]
@Fausto95 Contact ProxyPay (info@proxypay.co.ao) and they will set an account for you.
